### PR TITLE
Fix/transporters

### PR DESCRIPTION
**Pull request by tjasakumelj**
### Main improvements in this PR:
*Try to be as clear as possible: Is it fixing/adding something in the model? Is it an additional test/function/dataset?*

We evalueated, refined and updated transporter data in the model. Based on the genome annotation of Streptomyces coelicolor, all of the integral membrane transport proteins were extracted from the Transport Classification Database(TCDB).  Gene association for some of the existing transport reactions were changed/updated. There were also new transport reactions with existing and new metabolites integrated into the scoGEM model (three tables with these transporters: existing transporters with updated gene association, new transporters with existing and new metabolites ere uploaded intothe branch fix/transporters). When integrating transporter rxns into scoGEM model, rxnID, rxn formula, gene association, reversibility (lower and upper bound) were integrated into scoGEM model . In addition directionality from reversible to irreversible of the rxns with rxnID: VALTA, LEUTA, ILETA have been intoduced into the model. 
Gene association was defined based on  BLAST search of protein FASTA sequence (similarity score >= 90%). Substrates, taken by the transporters were either extracetd from TCDB, literature data (experimentally defined) or defined my the homology SMART BLAST search with the similarity score of >=90%. The scoGEM model after the transpoter updated, have been tested on growth for all the carbon and nitrogen sources, available in the scoGEM model as well as the evaluation has been done on mutant growth for specific mutants. All the growth data have benn compared to in vivo growth, iKS1317 GEM model growth and iMK1208 model growth (wild type growth table for C, N-sources and mutant growth rate table were uplodaed into the branch fix/transporters as well).

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/sco-GEM#required-software) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM) about this PR

*Note: replace [ ] with [X] to check the box.*

### CODE REVIEW

**Comment by tjasakumelj** [comment]
I have uploaded script for integration transporters into scoGEM model. I have deleted some of the data and left just the tables, including data pulled by script. Uploaded is scoGEM model fule in xml format, that inludes added transporters. Note:  yml file has not been created for the latest scoGEM.xml.

**Comment by tjasakumelj** [comment]
working on the branch-will try to finish today.

**Comment by tjasakumelj** [comment]
I have now gone through the requested changes and updated scoGEM.xml and correspondant scoGEM.yml on fix/transporters/ModelFiles and updated fix/transporters/ComplementaryScripts. Let me know if there are any additional comments before the merging can proceed.

**Comment by tjasakumelj** [comment]
I have now applied all the requested changes and accordingly updates scoGEM.xml and correspondant scoGEM.yml on fix transporters/ModelFiles and updated fix/transporters/ComplementaryScripts. Therefore I am sending a pool request to merge the model scoGEM.xml(yml), updated with transporters from the brench fix/transporters into master.

**Comment by tjasakumelj** [comment]
I have now updated scoGEM model for transport .
Sink reactions for new metabolites of new transport rxns were extracted from the model
Double reactions were removed
Tables for EXTransportRxns.xcsv, newTransportRxns.csv, updated_grRules.csv, newTransport_newMets.csv, were updated on fix/transporters/ComplementaryData/curration/trasnport_reactions
Table for the annotation of new metabolies in new transport reactions was uploaded
aresnite efflux rxns and its annotation was resolved
gamma-actinorhodin was resolved.
I have integrated changes inot scoGEM model on fix/transporters/ModelFiles/xml/scoGEM

**Comment by tjasakumelj** [comment]
Tables for transporters have been updated (doubles have been extracted) and additional column (H) on annotation of transporters and gene annotation for updated grRules have been added. As well as table for new metabolites with various annotations (\KEGG, BioCyc, MetaNetx).

**Comment by sulheim** [comment]
I think I messed it up slightly when fixing merge conflicts on my desktop. This pull request is now merged, although it doesn't show up here.
See commit:
https://github.com/SysBioChalmers/Sco-GEM/commit/9353c49eeb99ee5e6ea53463db3bdb17b9be8a45

**Pull request merged**
