### PR TITLE
Sco-GEM 1.3.0

### LINKED ISSUE #15: chore: initiate Sco-GEM repo
scoGEM development will be tracked on GitHub, this requires some setting up and maintenance
- [x] Initiate repo with text files (readme, license etc.)
- [x] Define contribution guidelines
- [x] Include iKS1317 in ModelFiles folder as initial scoGEM
- [x] Prepare issue and pull request templates
- [x] Export function that writes model as SBML and YAML. (now tracked in #37)
- [x] Update documentation before release

For the sake of reproducibility and ensuring that code and models remain available and citable, even if something would happen with GitHub, it would be good to link the repo to Zenodo. This way, everytime a new release is made, it will be automatically be stored on Zenodo and assigned a DOI.

Also see this discussion: https://twitter.com/rmflight/status/1052276442007068672

- [x] Setup link between GitHub and Zenodo, to be done once repo is public.
- [x] Mention Zenodo in README, and detail how citations to sco-GEM and different model versions should be handled

### LINKED ISSUE #33: fix: ids and annotation bugs
### Description of the issue:
I have discovered a couple of bugs in the annotation /ids of the metabolites including:
- "_c or _e" appended to BiGG annotations (e.g bigg.metabolite: actACPmmy_c)
- "_c" appended to biocyc annotations (e.g biocyc: CPD-209_c)
- metabolite malonyl-mmyA has id: *temp*. Should be malACPmmy_c
- metabolite with name acetoacetyl-mmyA has id: *malACPmmy_c*.  Should be *actACPmmy_c*
- empty annotations (i.e kegg.compound: '')
- Some biocyc annotations has *NADH* or *NADPH* appended
- Metabolite 44dpcopd_c should have KEGG ID C21770
- Correct reaction ID PSEDUO_ACCEPTOR_NADP

#### Tasks
- [x] Remove "_c or _e" from all BiGG  annotations
- [x] Remove "_c" from all biocyc  annotations
- [x] Fix ids of metabolites malACPmmy_c and temp
- [x] Remove empty annotations
- [x] Remove appended NADH or NADPH from biocyc annotations
- [x] Give metabolite 44dpcopd_c KEGG ID C21770
- [x] Correct reaction ID PSEDUO_ACCEPTOR_NADP

### LINKED ISSUE #44: feat: additional annotations
### Description of the issue:
Some additional information currently only available in spreadsheets should be added as annotations to the reactions:
- doi annotations (https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000019)
- Confidence scores / evidence annotation (https://github.com/draeger-lab/ModelPolisher/issues/5)

Also, from iAA1259 they have:
 - gene annotation has been expanded to Gene Ontology, Ensembl, and RefSeq
- Protein information (UniProt, Pfam, and Panther) and key reference data, such as protein sequence, length, and mass

I am not sure how this information should be stored, one option is to add the e.g. gene annotations into the SBML-file, and keep protein annotations as a separate csv-file in the ComplementaryData folder

#### To do:
- [x] Gather doi information from iAA1259, Sco4 and iKS1317
- [x] Add doi annotations to model
- [ ] Evidence based annotation (when implemented in cobrapy)
- [x] Add gene annotations from iAA1259
- [x] Upload protein information to repo / or store in a different way

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist

### LINKED ISSUE #62: fix: Invalide KEGG ids
### Description of the issue:
In supplementary table S10 from Sco4, a list of invalid KEGG identfiers and the replacements are found. These changes should be incorporated in ScoGEM

Table S10: Complete list of invalide KEGG identifiers   and the replacements.
--
*Invalid KEGG* | *Updated KEGG* | *MetaCyc ID*
----------------|--------------------|----------------
**iMK1208** | **Sco4** | **MetaCyc ID**
C00661 | C00118 | GAP
C00507 | C02338 | CPD0-1112
C00311 | C00451 | THREO-DS-ISO-CITRATE
C01602 | C00077 | L-ORNITHINE
C00348 | C17556 | CPD-9646
C00023 | C14818 | FE+2
C00725 | C16241 | LIPOIC-ACID
C06717 | C00051 | GLUTATHIONE
C01551 | C02350 | S-ALLANTOIN
C03340 | C20258 | CPD-14443
C01188 | C06001 | CPD-12175
C00034 | C19610 | MN+2
C00291 | C19609 | NI+2
C07597 |   | CPD-11957

#### To do:
- [x] Fix changes given above

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #64: feat: Name cpk genes
### Description of the issue:
Genes related to Coelimycin biosynthesis are not given nam (only SCO numbers).
The names are given in Pawlik, K., Kotowska, M., Chater, K.F. et al. Arch Microbiol (2007) 187: 87. https://doi.org/10.1007/s00203-006-0176-7

#### Expected feature/value/output:
cpk related genes given correct name, e.g:
(from YAML-file):
- id: SCO6275
- name: CpkA

#### Current feature/value/output:
- id: SCO6275
- name: ''

#### To do:
- [x] Use table provided in the given publication to update gene names
- [x] Include this in the ScoGEM reconstruction.

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #65: docs: link repo to Zenodo
### Description of the issue:
To ensure future data availability we want to store a snapshot of the repository on [Zenodo](https://zenodo.org/) on every new release of the model.
 More information on how to do this is given her
https://guides.github.com/activities/citable-code/

**I hereby confirm that:**
- [x] A similar issue does not already exist

### LINKED ISSUE #87: fix: direction of ICDhyr (isocitrate dehydrogenase)
### Description of the issue:
The reaction ICDhyr [R00267](https://www.genome.jp/dbget-bin/www_bget?rn:R00267+R01899+R00268) is actually a two-step reaction where the second step is irreversible (dG of -32 kJ/mmol). The reaction combined has a dG of -10, and it is therefor set to reversible, which is not true.

#### Expected feature/value/output:
The optimal solution is to replace ICDhyr by the two reactions and make the second reaction irreversible. Another option is to just make the ICDhyr irreversible.

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [x] Decide on a solution and make changes to the reconstruction script
- [x] Update model files

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #88: feat: include cofactor information from Coze et al., 2013
From [Coze et al., 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3871631/) we have: *We found that glucose-6-phosphate dehydrogenase was strictly NADP-dependent, with a specific activity of 144.662.7 mmol/min/mg protein and no detectable activity with NAD. Furthermore, we found that 6-phosphogluconate dehydrogenase was strictly NADP-dependent, with a specific activity of 236.466.4 mmol/min/mg protein and no detectable activity with NAD. We also verified that isocitrate dehydrogenase was strictly NADP-dependent, with a specific activity of 132.764.3 mmol/min/mg protein and no activity at all with NAD.*

Therefore, reactions with the wrong cofactors should be deleted, and this can probably be mentioned in the note field of the correct cofactor-related reaction and with a doi annotation to Coze et al., 2013, in the annotation field.
The following reactions should then be deleted:
- G6PDH1b
- GND2

#### To do:
- [x] Incorporate changes into reconstruction script and 
- [x] Reconstruct xml and yml model files

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #89: fix: alpha and beta variants of glucose-6-phosphate
There is currently 3 versions of glucose-6-phosphate in the model:
- General form g6p_c (In 10 reactions)
- Beta form g6p_B_c (In 6 reactions)
- Alpha form g6p_A_c (In 2 reactions)

From [HMDB](http://www.hmdb.ca/metabolites/HMDB0003498) we have *... Specifically, beta-D-Glucose 6-phosphate is glucose sugar phosphorylated on carbon 6. It is a very common metabolite in cells as the vast majority of glucose entering a cell will become phosphorylated in this way.*

### Description of the issue:
It is currently a bit messy to have all three variants. We can either:
1) Use only the general form (g6p_c)
2) Use both the the alpha and beta form (But then what form should the currently general form be assigned to?
3) Keep all of them and have isomerases between all the three pairs (currently only between g6p_A_c and g6p_B_c)

This differences propagates to some extent into fructose 6-phosphate and maybe a few other compounds. 

#### Expected feature/value/output:
A clean, tidy solution which reduce unnecessary mess while keeping important details.

#### To do:
- [ ] Agree on a solution for glucose 6-phosphate and a general solution for similar issues
- [ ] Find out which reactions and which related compounds that are affected
- [ ] Generate script for performing curation and update model files

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #90: fix: direction of ferredoxin-NAPD reductase
### Description of the issue:
The reaction putative ferredoxin/ferredoxin-NADP reductase  (FNOR) is now reversible in the model, but according to this [paper](https://doi.org/10.1016/j.abb.2008.02.014) it is only used to consume NADPH and produce reduced ferredoxin in non-photosynthetic bacteria.

#### To do:
- [x] Make reaction irreversible, add note and doi annotation

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #100: Check if SCO2529 really is a catalase
### Description of the issue:
Uniprot annotation is metalloproteinase, and the gene expression trends are very different from teh other catalase. It is possible that we should remove this gene from the catalase function. 

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #104: Fix duplicated reactions
### Description of the issue:
The following reactions are duplicated in terms of substrates  / products (but not gene annotation):
- GABTA and ABPYRATA
- CA2abc1 and AMEt

Figure out which one of these that should be deleted / modified / kept

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [ ] E.g. generate script for performing curation

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #105: fix: clean-up annotations
### Description of the issue:
Some overlap with #33 and #44, but bigger scope here. If this issue is settled, then the other two can also be closed.

Various (minor) issues exist with current annotations of genes, mets and rxns:
- [x] 1. `metanetx` is sometimes misspelled as `metabetx`
- [x] 2. About 21 metabolites are annotated to `3dmet`. Either annotate all metabolites (as far as possible) to this database, or drop the annotation of these few metabolites. This is not a [database](http://www.3dmet.dna.affrc.go.jp/met_index.php) commonly used for GEMs, the model is not using 3D structures of metabolites, so drop the annotation.
- [x] 3. About 19 metabolites are annotated to `cas`. Either annotate all metabolites (as far as possible) to this database, or drop the annotation of these few metabolites. This is not a [database](https://www.cas.org/support/documentation/chemical-substances) commonly used for GEMs, so drop the annotation.
- [x] 4. About 27 metabolites are annotated to `pubchem.substance`. The more common database is `pubchem.compound`. Drop the `pubchem.substance` annotation and make sure that the `pubchem.compound` is included for those metabolites.
- [x] 5. Only N-Acetyl-L-Cysteine is annotated to `kegg.drugs`, while `kegg.compound` is also defined. Drop the `kegg.drugs` annotation.
- [x] 6. Some ChEBI annotations are misrepresented, as `CHEBI%3A15377` instead of `CHEBI:15377`. Each of the metabolites is also annotated with the correct ChEBI annotation: remove the incorrect ones.

- [x] 7. About 17 reactions are annotated to `kegg.ontology`. This is mostly redundant to the more commonly used `kegg.reactions`, which are annotated to 1369 reactions (including the 17 reactiosn with `kegg.ontology`). Drop the annotation.

- [ ] ~~8. Of the 1778 genes, 215 are annotated with GO terms. Should this be extended to all genes, or should `go` as annotation be dropped?~~ See #44
- [ ] ~~9. Of the 1778 genes, 219 are annotated with PFAM domains. Should this be extended to all genes, or should `pfam` as annotation be dropped?~~ See #44

#### Expected feature/value/output:

- Do not include sporious annotations to databases that are not commonly used:
  - Either remove the uncommon database, ...
  - ... or increase the coverage to all members.
- Improve coverage of common annotations (e.g. SEED, currently covering 1.9% of metabolites), will be handled in a separate issue.

#### To do:
If agreed to remove the sporious annotations to uncommon databases, to do list will be included here.

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #106: Block / Remove reaction R10221
The activity of phosphogluconate dehydrogenase in _S. coelicolor_ with NAD and NADP is tested by [Coze et al., 2013](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0084151). They find that this enzyme is strictly NADP dependent, so  I think we can remove R10221.

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #110: Unclear what the different model files represent
We wonder what is the "official" SBML Sco-GEM model in the ModelFiles/xml/ repository.

XML/SBML files have different size, different last modification time, and for some of them a cryptic name.

### LINKED ISSUE #111: Invalid annotations?
Hi

some annotations don't look to be valid in the **Sco-GEM.xml** file:

- ec-code: according to identifiers.org ec-code annotations must contain a single EC number.
  For cases with multiple EC numbers, I think you have to duplicate the annotations.
  Don't know really how to deal with OR
  And not sure what you mean with the comma: "2.7.1.11, 2.7.1.56, 2.7.1.144". AND or OR ?
  e.g. "https://identifiers.org/ec-code/&quot;1.2.4.2 and 1.8.1.4 and 2.3.1.61&quot;"
         "https://identifiers.org/ec-code/1.1.1.1 or 1.1.99.1"
         "https://identifiers.org/ec-code/2.7.1.11, 2.7.1.56, 2.7.1.144"

- kegg.reaction: according to identifiers.org kegg.reaction must contain a single KEGG reaction id.
  I think you have to duplicate the annotations.
  Again not sure what you mean with the comma.
  e.g. "https://identifiers.org/kegg.reaction/[&apos;R02075&apos;, &apos;R08836&apos;]"

- doi/PMID: is not valid according to identifiers.org registry for doi
  Better to use https://registry.identifiers.org/registry/pubmed for PMID
  e.g. "https://identifiers.org/doi/PMID: 16554727" should be https://identifiers.org/pubmed/16554727

### LINKED ISSUE #124: doc: delete gitter repo and update related docs
### Description of the issue:
With the newly added Discussion feature on GitHub I don't see the need for an additional gitter repository.  I therefore suggest that we delete that repository and edit our issue templates / documentation / badges to remove any pointers to gitter.

#### To Do
- [x] Post on current  [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM) that discussions are moved here
- [x] Update readme
- [x] Update issue template

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #136: bug: two unnecessary boundary metabolites
### Description of the issue:
Two exchange reactions included from iAA1259 contains so-called boundary metabolites, i.e.:
 - cellul_e_boundary
 - xylan_e_boundary
Remove these metabolites

#### Expected feature/value/output:
(from yaml-file)
- id: EX_cellul_e
    - name: Cellulose exchange reaction
    - metabolites: !!omap
      - cellul_e: -1.0
    - lower_bound: 0.0
    ....

- id: EX_xylan_e
    - name: Xylan exchange reaction
    - metabolites: !!omap
      - xylan_e: -1.0
    - lower_bound: 0.0
    .....

#### Current feature/value/output:
- id: EX_cellul_e
    - name: Cellulose exchange reaction
    - metabolites: !!omap
      - cellul_e: -1.0
      - cellul_e_boundary: 1.0
    - lower_bound: 0.0
    ....

- id: EX_xylan_e
    - name: Xylan exchange reaction
    - metabolites: !!omap
      - xylan_e: -1.0
      - xylan_e_boundary: 1.0
    - lower_bound: 0.0
    .....

#### Reproducing these results:
Check model file

#### To do:
- [ ] E.g. generate script for performing curation

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- fix:
  - correct biocyc annotation ZCAROTDH2 (closes #33)
  - UniProt ID, PFAM, Panther, GO term and refseq annotations as gathered from Uniprot (closes #44)
  - correct invalid KEGG metabolite IDs identified in Sco4 paper (closes #62)
  - gene names are gathered from the Sanger genome annotation, strepDB, UniProt and additional literature (closes #64)
  - directionality of ICDHyr (closes #87)
  - remove reaction with incorrect co-factor (G6PDH1b) (closes #88)
  - remove unnecessary anomers of carbohydrates, only keeping the generic forms (closes #89)
  - directionality of ferredoxin-NAPD reductase (closes #90)
  - remove incorrect in GPR for CAT reaction (closes #100)
  - curated duplicated reactions, involved GABTA, ABPYRATA, CA2abc1 and AMEt (closes #104)
  - correct and deprecate multiple reaction and metabolite annotations (closes #105)
  - remove reaction GND2, wrong co-factor (closes #106)
  - remove multiple annotations when only one is correct (KEGG, ec-code) (closes #111)
  - acetyl-CoA rewiring from iKS1317 (closes #129)
  - remove unused genes, not annotated to any reaction
  - remove inconsistent and unnecessary `<notes>` entries, with information already covered elsewhere
  - `export.py` recognizes `sbo` terms, adheres to [standard-GEM](https://github.com/MetabolicAtlas/standard-GEM), include subroutine to load previous releases of the model (`export.get_earlier_model_unversioned`) 
  - remove two unnecessary boundary metabolites (closes #136)

- feat:
  - protein sequence, length and mass are gathered from UniProt (closes #44)
  - `increaseVersion.py` function that should be run on master branch to prepare a new version release (closes #133)
  - template curation script `code/curation/vx_x_x.py`

- refactor:
  - renamed folders and reformatted README.md to adhere to [standard-GEM](https://github.com/MetabolicAtlas/standard-GEM)
  - all model files (`xml` and `yml` for now) are located in the `model/` folder (closes #110)
  - moved scripts, data and ec-models specific for Sulheim _et al._ (2020) to dedicated folders in /code and /data (closes #110)
  - separate requirements.txt for `code/sulheim2020/`, reducing the packages in `/requirements.txt`
  - I/O by latest cobrapy (0.20) adds zero charge for metabolites whose charge was previously not specified (hence, metabolite charges should be curated, see #79)

- doc:
  - add Zenodo batch (closes #15, closes #65)
  - point to GitHub Discussions instead of Gitter (closes #124)
  - update contributing guidelines, move to `.github` folder (closes #133)

- chore:
  - add model.id field (closes #130)

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/sco-GEM#required-software) for running the model
- [x] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by sulheim** [comment]
- [ ] Rerun the memote tests (including the custom growth / knockout phenotypes test) and assure that the accuracy is the same
- [ ] Update memote report

**Comment by sulheim** [comment]
One concern with the current implementation of the curation script is that it is inconvenient to test the *v_1_3_0.py* since it needs the model version 1.2.0 to run. And currently, the model version in the repository is not 1.2.0. 
Not sure how we should solve this. We could of course save intermediate model versions in an archive that can be used as input? What do you think?

**Comment by edkerk** [comment]
True. Another strategy would be to have a `v1_3_0.py` script that gathers the various curations, while having the individual scripts (each referring to one Issue?) in a subfolder. Then, `v1_3_0.py` could be coded to check that the model "input" is the previous model version (or could even specifically load that release using git), before running all individual scripts and finally generating all output.

**Comment by sulheim** [comment]
I think it would be too many files if we strictly have one file per issue. Hower, on a higher level your suggestion might work. E.g. A general reconstruction scipt that checks model version before it calls `v_1_3_0.py.`
Actually, I think it would be nice to bring this discussion up in the Standard-GEM development, as I am sure this is not a concern that is limited to the Sco-GEM development. What do you think?
I guess this is partially overlapping with https://github.com/MetabolicAtlas/standard-GEM/issues/20

**Comment by edkerk** [comment]
It is indeed a universal issue, discussion in `standard-GEM` would make sense.

One script per issue might indeed be too much, perhaps multiple smaller issues could be combined in a script e.g. `v1_3_0/misc_curations.py` script, while larger issues could have their own dedicated script e.g. `v1_3_0/feat_reassign_all_metabolite_annotations.py`.

One issue I can see is that the model version number will not be known until PR to `master`, so instead of `v1_3_0/` this folder could be named `latest/`, and renamed to the desired version number in `devel` before making PR to `master`. However, if these paths are also hard-coded in any scripts, then that would also have to be changed.

Easiest way is then not to name scripts by their version number or collect them in folders named with version number. Instead, the functions and data are in appropriate subfolders of `code/` and `data/` (for instance `../biomass/` or `../reversibility/`, while still having a collecting script `v1_3_0.py` that checks model version before calling the appropriate functions.

**Comment by sulheim** [comment]
I still think that it might make sense to have a `model/archive` folder. A pull reuqest from devel to master that cause a minor bup in version could archive the xml-version of that model. Thus, in the `model` folder you can always find the latest model version, but if you need the previous version for testing you can easily do that.

**Comment by edkerk** [comment]
> * [x]  Rerun the memote tests (including the custom growth / knockout phenotypes test) and assure that the accuracy is the same
> * [ ]  Update memote report

- Custom tests:
  - Knockouts from transposon data: one less TP, as the **unused** gene SCO3946 was present in the previous model version and thereby a "false true positive". This gene is now not in the model and therefore not tested for essentiality.
  - Knockouts from literature data: one more TP, but also one additional FN: SCO2726 at different carbon sources. Accuracy therefore unchanged.
- Memote (run locally):
  - Stoichiometric Consistency test has changed (Memote version 0.12.0 vs. 0.9.12). Overall score dropped from 77% to 72%.
  - When running Memote 0.12.0 on the previous release, overall score increased from 71% to 72%.

Will include code that runs Memote locally with each release.

**Review by sulheim — APPROVED** [review]
Great work! A very nice minor version bump 👍 Nice to get so many of those issues resolved.

**Pull request merged**
