### PR TITLE
fix: annotations and minor reaction curations 

### LINKED ISSUE #33: fix: ids and annotation bugs
### Description of the issue:
I have discovered a couple of bugs in the annotation /ids of the metabolites including:
- "_c or _e" appended to BiGG annotations (e.g bigg.metabolite: actACPmmy_c)
- "_c" appended to biocyc annotations (e.g biocyc: CPD-209_c)
- metabolite malonyl-mmyA has id: *temp*. Should be malACPmmy_c
- metabolite with name acetoacetyl-mmyA has id: *malACPmmy_c*.  Should be *actACPmmy_c*
- empty annotations (i.e kegg.compound: '')
- Some biocyc annotations has *NADH* or *NADPH* appended
- Metabolite 44dpcopd_c should have KEGG ID C21770
- Correct reaction ID PSEDUO_ACCEPTOR_NADP

#### Tasks
- [x] Remove "_c or _e" from all BiGG  annotations
- [x] Remove "_c" from all biocyc  annotations
- [x] Fix ids of metabolites malACPmmy_c and temp
- [x] Remove empty annotations
- [x] Remove appended NADH or NADPH from biocyc annotations
- [x] Give metabolite 44dpcopd_c KEGG ID C21770
- [x] Correct reaction ID PSEDUO_ACCEPTOR_NADP

### LINKED ISSUE #62: fix: Invalide KEGG ids
### Description of the issue:
In supplementary table S10 from Sco4, a list of invalid KEGG identfiers and the replacements are found. These changes should be incorporated in ScoGEM

Table S10: Complete list of invalide KEGG identifiers   and the replacements.
--
*Invalid KEGG* | *Updated KEGG* | *MetaCyc ID*
----------------|--------------------|----------------
**iMK1208** | **Sco4** | **MetaCyc ID**
C00661 | C00118 | GAP
C00507 | C02338 | CPD0-1112
C00311 | C00451 | THREO-DS-ISO-CITRATE
C01602 | C00077 | L-ORNITHINE
C00348 | C17556 | CPD-9646
C00023 | C14818 | FE+2
C00725 | C16241 | LIPOIC-ACID
C06717 | C00051 | GLUTATHIONE
C01551 | C02350 | S-ALLANTOIN
C03340 | C20258 | CPD-14443
C01188 | C06001 | CPD-12175
C00034 | C19610 | MN+2
C00291 | C19609 | NI+2
C07597 |   | CPD-11957

#### To do:
- [x] Fix changes given above

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #87: fix: direction of ICDhyr (isocitrate dehydrogenase)
### Description of the issue:
The reaction ICDhyr [R00267](https://www.genome.jp/dbget-bin/www_bget?rn:R00267+R01899+R00268) is actually a two-step reaction where the second step is irreversible (dG of -32 kJ/mmol). The reaction combined has a dG of -10, and it is therefor set to reversible, which is not true.

#### Expected feature/value/output:
The optimal solution is to replace ICDhyr by the two reactions and make the second reaction irreversible. Another option is to just make the ICDhyr irreversible.

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [x] Decide on a solution and make changes to the reconstruction script
- [x] Update model files

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #90: fix: direction of ferredoxin-NAPD reductase
### Description of the issue:
The reaction putative ferredoxin/ferredoxin-NADP reductase  (FNOR) is now reversible in the model, but according to this [paper](https://doi.org/10.1016/j.abb.2008.02.014) it is only used to consume NADPH and produce reduced ferredoxin in non-photosynthetic bacteria.

#### To do:
- [x] Make reaction irreversible, add note and doi annotation

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #104: Fix duplicated reactions
### Description of the issue:
The following reactions are duplicated in terms of substrates  / products (but not gene annotation):
- GABTA and ABPYRATA
- CA2abc1 and AMEt

Figure out which one of these that should be deleted / modified / kept

#### To do:
*If specific curations are proposed, generate a list of checkboxes of steps that should be followed to solve this issue:*
- [ ] E.g. generate script for performing curation

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #106: Block / Remove reaction R10221
The activity of phosphogluconate dehydrogenase in _S. coelicolor_ with NAD and NADP is tested by [Coze et al., 2013](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0084151). They find that this enzyme is strictly NADP dependent, so  I think we can remove R10221.

**I hereby confirm that:**
- [x] This problem persists in the `master` branch of the repository
- [x] A similar issue does not already exist
- [x] I've considered asking this first in the [Gitter chat room](https://gitter.im/SysBioChalmers/sco-GEM)

### LINKED ISSUE #111: Invalid annotations?
Hi

some annotations don't look to be valid in the **Sco-GEM.xml** file:

- ec-code: according to identifiers.org ec-code annotations must contain a single EC number.
  For cases with multiple EC numbers, I think you have to duplicate the annotations.
  Don't know really how to deal with OR
  And not sure what you mean with the comma: "2.7.1.11, 2.7.1.56, 2.7.1.144". AND or OR ?
  e.g. "https://identifiers.org/ec-code/&quot;1.2.4.2 and 1.8.1.4 and 2.3.1.61&quot;"
         "https://identifiers.org/ec-code/1.1.1.1 or 1.1.99.1"
         "https://identifiers.org/ec-code/2.7.1.11, 2.7.1.56, 2.7.1.144"

- kegg.reaction: according to identifiers.org kegg.reaction must contain a single KEGG reaction id.
  I think you have to duplicate the annotations.
  Again not sure what you mean with the comma.
  e.g. "https://identifiers.org/kegg.reaction/[&apos;R02075&apos;, &apos;R08836&apos;]"

- doi/PMID: is not valid according to identifiers.org registry for doi
  Better to use https://registry.identifiers.org/registry/pubmed for PMID
  e.g. "https://identifiers.org/doi/PMID: 16554727" should be https://identifiers.org/pubmed/16554727

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- fix
  - correct biocyc annotation ZCAROTDH2 (closes #33)
  - correct invalid KEGG metabolite IDs identified in Sco4 paper (closes #62)
  - directionality of ICDHyr (closes #87)
  - directionality of ferredoxin-NAPD reductase (closes #90)
  - curated duplicated reactions, involved GABTA, ABPYRATA, CA2abc1 and AMEt (closes #104)
  - correct and deprecate multiple reaction and metabolite annotations (#105) **not done yet**
  - remove reaction GND2, wrong co-factor (closes #106)
  - remove multiple annotations when only one is correct (KEGG, ec-code) (closes #111)

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/sco-GEM#required-software) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by sulheim** [comment]
Great work! 
Should `curate/v130.py` be called in `reconstruct_ScoGEM.py`, or how do you plan to move forward when later updates are introduced?

**Review by sulheim — APPROVED** [review]
Looks good.

**Comment by edkerk** [comment]
@sulheim Instead of one script generating the latest Sco-GEM version from scratch, it's probably more convenient to have scripts to update from one release to the next. In the future there might be changes in software that would break the earlier scripts (perhaps not seriously, but requiring changes anyway), so pretending that the model can always be regenerated completely from iKS1317, Sco4 and the other one would just take more work.
Now I've coded all changes in `v130.py`, but it could also function as "`reconstruct_ScoGEM.py`" for each release by combining separate scripts with changes. However, each release is likely to have much less changes then the massive work to reconstruct Sco-GEM.
Note that I'll make a few more commits to this PR, regarding #105 and documentation of `v130.py` (could also be named differently?). And yes, it closes a bunch of issues, will modify the PR message to automate.

**Comment by edkerk** [comment]
One issue I've noticed is that `export.py` is in `/code` while further (curation) scripts would be in child folders, which means that `export.py` cannot easily be imported in those scripts. As a workaround, we could have a `latest_changes.py` placeholder script in `/code`, which calls the latest update script (`/code/curate/v130.py` in this case) and then runs `export`, and this placeholder script should be updated after each release to refer to the latest update script.

Or any other solution?

**Comment by sulheim** [comment]
I think your suggestion makes sense. Otherwise, one could always add the parent folder to path with `sys.path.append("..")`, but I think your suggestion is better. We could potentially add version number to the model id in the xml-file (so the `latest_changes.py`) don't run `v130.py` if the model already has those curations. Anyway, the final solution should be stated in the README

**Comment by sulheim** [comment]
By the way. should we add the GitHub discussion feature (and possibly discard the gitter repo)?

**Pull request merged**
